# swiftlint.yml

disabled_rules:
    - trailing_whitespace
    - force_cast

opt_in_rules:
    - empty_count
    - explicit_init
    - force_unwrapping

included:
    - Sources

excluded:
    - Tests

line_length:
    warning: 120
    error: 150

type_body_length:
    warning: 400
    error: 500

force_unwrapping:
    severity: warning
