# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    macos:
      xcode: "16.0"
    steps:
      - checkout
      - run:
          name: Build the library
          command: xcodebuild -scheme OdooRPC -sdk macosx -destination 'platform=macOS' build

 test:
    macos:
      xcode: "16.0"
    steps:
      - checkout
      - run:
          name: Run tests
          command: xcodebuild test -scheme OdooRPC -sdk macosx -destination 'platform=macOS'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
