# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  ios-executor:
    macos:
      xcode: "16.0" 

jobs:
  build:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Build the project
          command: xcodebuild -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' build

  test:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: xcodebuild test -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
